spring.application.name=IA Bot

# Banco de Dados
spring.datasource.url=jdbc:${SPRING_DATASOURCE_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.jpa.hibernate.ddl-auto=update
# --- GOOGLE GEMINI ---
spring.ai.google.ai.gemini.api-key=${GOOGLE_API_KEY}
spring.ai.google.ai.gemini.chat.options.model=gemini-1.5-flash
#---GROQ---
spring.ai.openai.api-key=${SPRING_AI_OPENAI_API_KEY}
spring.ai.openai.base-url=${SPRING_AI_OPENAI_BASE_URL}
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

